/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BuildWithWhatIHaveRouteImport } from './routes/build-with-what-i-have'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as ReuseRouteImport } from './routes/reuse'
import { Route as VisionAnalysisRouteImport } from './routes/vision-analysis'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWithWhatIHaveRoute = BuildWithWhatIHaveRouteImport.update({
  id: '/build-with-what-i-have',
  path: '/build-with-what-i-have',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ReuseRoute = ReuseRouteImport.update({
  id: '/reuse',
  path: '/reuse',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionAnalysisRoute = VisionAnalysisRouteImport.update({
  id: '/vision-analysis',
  path: '/vision-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/build-with-what-i-have': typeof BuildWithWhatIHaveRoute
  '/dashboard': typeof DashboardRoute
  '/identify': typeof IdentifyRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/reuse': typeof ReuseRoute
  '/vision-analysis': typeof VisionAnalysisRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/build-with-what-i-have': typeof BuildWithWhatIHaveRoute
  '/dashboard': typeof DashboardRoute
  '/identify': typeof IdentifyRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/reuse': typeof ReuseRoute
  '/vision-analysis': typeof VisionAnalysisRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/build-with-what-i-have': typeof BuildWithWhatIHaveRoute
  '/dashboard': typeof DashboardRoute
  '/identify': typeof IdentifyRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/reuse': typeof ReuseRoute
  '/vision-analysis': typeof VisionAnalysisRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/build'
    | '/build-with-what-i-have'
    | '/dashboard'
    | '/identify'
    | '/inventory'
    | '/knowledge'
    | '/profile'
    | '/projects'
    | '/repair'
    | '/reuse'
    | '/vision-analysis'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/build'
    | '/build-with-what-i-have'
    | '/dashboard'
    | '/identify'
    | '/inventory'
    | '/knowledge'
    | '/profile'
    | '/projects'
    | '/repair'
    | '/reuse'
    | '/vision-analysis'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/auth'
    | '/build'
    | '/build-with-what-i-have'
    | '/dashboard'
    | '/identify'
    | '/inventory'
    | '/knowledge'
    | '/profile'
    | '/projects'
    | '/repair'
    | '/reuse'
    | '/vision-analysis'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  BuildWithWhatIHaveRoute: typeof BuildWithWhatIHaveRoute
  DashboardRoute: typeof DashboardRoute
  IdentifyRoute: typeof IdentifyRoute
  InventoryRoute: typeof InventoryRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  RepairRoute: typeof RepairRoute
  ReuseRoute: typeof ReuseRoute
  VisionAnalysisRoute: typeof VisionAnalysisRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-with-what-i-have': {
      id: '/build-with-what-i-have'
      path: '/build-with-what-i-have'
      fullPath: '/build-with-what-i-have'
      preLoaderRoute: typeof BuildWithWhatIHaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reuse': {
      id: '/reuse'
      path: '/reuse'
      fullPath: '/reuse'
      preLoaderRoute: typeof ReuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-analysis': {
      id: '/vision-analysis'
      path: '/vision-analysis'
      fullPath: '/vision-analysis'
      preLoaderRoute: typeof VisionAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  BuildWithWhatIHaveRoute: BuildWithWhatIHaveRoute,
  DashboardRoute: DashboardRoute,
  IdentifyRoute: IdentifyRoute,
  InventoryRoute: InventoryRoute,
  KnowledgeRoute: KnowledgeRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  RepairRoute: RepairRoute,
  ReuseRoute: ReuseRoute,
  VisionAnalysisRoute: VisionAnalysisRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
